# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys

m_red_SheetStyle = "min-width: 16px; min-height: 16px;max-width:16px; max-height: 16px;border-radius: 8px;  border:1px solid black;background:red";
m_green_SheetStyle = "min-width: 16px; min-height: 16px;max-width:16px; max-height: 16px;border-radius: 8px;  border:1px solid black;background:green";
m_grey_SheetStyle = "min-width: 16px; min-height: 16px;max-width:16px; max-height: 16px;border-radius: 8px;  border:1px solid black;background:grey";
m_yellow_SheetStyle = "min-width: 16px; min-height: 16px;max-width:16px; max-height: 16px;border-radius: 8px;  border:1px solid black;background:yellow";


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(495, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 440, 75, 23))
        self.pushButton.setObjectName("pushButton")

        # self.push_getconfig = QtWidgets.QPushButton(self.centralwidget)
        # self.push_getconfig.setGeometry(QtCore.QRect(40, 500, 75, 23))
        # self.push_getconfig.setObjectName("push_getconfig")

        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(140, 400, 291, 151))
        self.textEdit.setObjectName("textEdit")

        self.label_1_state = QtWidgets.QLabel(self.centralwidget)
        self.label_1_state.setGeometry(QtCore.QRect(40, 80, 54, 12))
        self.label_1_state.setObjectName("label_1_state")
        self.label_1_state.setStyleSheet(m_grey_SheetStyle)
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(120, 80, 54, 12))
        self.label_1.setObjectName("label_1")

        self.label_2_state = QtWidgets.QLabel(self.centralwidget)
        self.label_2_state.setGeometry(QtCore.QRect(40, 140, 54, 12))
        self.label_2_state.setObjectName("label_2_state")
        self.label_2_state.setStyleSheet(m_grey_SheetStyle)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 140, 54, 12))
        self.label_2.setObjectName("label_2")

        self.label_3_state = QtWidgets.QLabel(self.centralwidget)
        self.label_3_state.setGeometry(QtCore.QRect(40, 200, 54, 12))
        self.label_3_state.setObjectName("label_3_state")
        self.label_3_state.setStyleSheet(m_grey_SheetStyle)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 200, 54, 12))
        self.label_3.setObjectName("label_3")

        self.label_4_state = QtWidgets.QLabel(self.centralwidget)
        self.label_4_state.setGeometry(QtCore.QRect(40, 260, 54, 12))
        self.label_4_state.setObjectName("label_4_state")
        self.label_4_state.setStyleSheet(m_grey_SheetStyle)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(120, 260, 54, 12))
        self.label_4.setObjectName("label_4")

        self.label_5_state = QtWidgets.QLabel(self.centralwidget)
        self.label_5_state.setGeometry(QtCore.QRect(40, 330, 54, 12))
        self.label_5_state.setObjectName("label_5_state")
        self.label_5_state.setStyleSheet(m_grey_SheetStyle)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(120, 330, 54, 12))
        self.label_5.setObjectName("label_5")

        self.label_6_state = QtWidgets.QLabel(self.centralwidget)
        self.label_6_state.setGeometry(QtCore.QRect(270, 80, 54, 12))
        self.label_6_state.setObjectName("label_6_state")
        self.label_6_state.setStyleSheet(m_grey_SheetStyle)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(350, 80, 54, 12))
        self.label_6.setObjectName("label_6")

        self.label_7_state = QtWidgets.QLabel(self.centralwidget)
        self.label_7_state.setGeometry(QtCore.QRect(270, 140, 54, 12))
        self.label_7_state.setObjectName("label_7_state")
        self.label_7_state.setStyleSheet(m_grey_SheetStyle)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(350, 140, 54, 12))
        self.label_7.setObjectName("label_7")

        self.label_8_state = QtWidgets.QLabel(self.centralwidget)
        self.label_8_state.setGeometry(QtCore.QRect(270, 200, 54, 12))
        self.label_8_state.setObjectName("label_8_state")
        self.label_8_state.setStyleSheet(m_grey_SheetStyle)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(350, 200, 54, 12))
        self.label_8.setObjectName("label_8")

        self.label_9_state = QtWidgets.QLabel(self.centralwidget)
        self.label_9_state.setGeometry(QtCore.QRect(270, 260, 54, 12))
        self.label_9_state.setObjectName("label_9_state")
        self.label_9_state.setStyleSheet(m_grey_SheetStyle)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(350, 260, 54, 12))
        self.label_9.setObjectName("label_9")

        self.label_10_state = QtWidgets.QLabel(self.centralwidget)
        self.label_10_state.setGeometry(QtCore.QRect(270, 330, 54, 12))
        self.label_10_state.setObjectName("label_10_state")
        self.label_10_state.setStyleSheet(m_grey_SheetStyle)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(350, 330, 54, 12))
        self.label_10.setObjectName("label_10")

        MainWindow.setCentralWidget(self.centralwidget)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")

        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 495, 22))
        self.menuBar.setObjectName("menuBar")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "下一个"))
        #self.push_getconfig.setText(_translate("MainWindow", "串口信息"))

        self.label_1_state.setText(_translate("MainWindow", "1"))
        self.label_1.setText(_translate("MainWindow", "UUT1"))

        self.label_2_state.setText(_translate("MainWindow", "2"))
        self.label_2.setText(_translate("MainWindow", "UUT2"))

        self.label_3_state.setText(_translate("MainWindow", "3"))
        self.label_3.setText(_translate("MainWindow", "UUT3"))

        self.label_4_state.setText(_translate("MainWindow", "4"))
        self.label_4.setText(_translate("MainWindow", "UUT4"))

        self.label_5_state.setText(_translate("MainWindow", "5"))
        self.label_5.setText(_translate("MainWindow", "UUT5"))

        self.label_6_state.setText(_translate("MainWindow", "6"))
        self.label_6.setText(_translate("MainWindow", "UUT6"))

        self.label_7_state.setText(_translate("MainWindow", "7"))
        self.label_7.setText(_translate("MainWindow", "UUT7"))

        self.label_8_state.setText(_translate("MainWindow", "8"))
        self.label_8.setText(_translate("MainWindow", "UUT8"))

        self.label_9_state.setText(_translate("MainWindow", "9"))
        self.label_9.setText(_translate("MainWindow", "UUT9"))

        self.label_10_state.setText(_translate("MainWindow", "10"))
        self.label_10.setText(_translate("MainWindow", "UUT10"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)  # 创建一个QApplication，也就是你要开发的软件app
    MainWindow = QtWidgets.QMainWindow()    # 创建一个QMainWindow，用来装载你需要的各种组件、控件
    ui = Ui_MainWindow()                    # ui是Ui_MainWindow()类的实例化对象
    ui.setupUi(MainWindow)                  # 执行类中的setupUi方法，方法的参数是第二步中创建的QMainWindow
    MainWindow.show()                       # 执行QMainWindow的show()方法，显示这个QMainWindow
    sys.exit(app.exec_())                   # 使用exit()或者点击关闭按钮退出QApplication